server:
  port: 9092
spring:
  jwt:
    secret: de1e9266dd159fa1641bbb6661fb8479b9c8e12ccf9a571d82faa93f5947b84c479679a34839e2a6c6d3fbffbb8feb6e03ae0ebb0846c3464a1a211ee0cd5e04

  datasource:
    url: jdbc:mysql://mingky.me/KUK?serverTimezone=Asia/Seoul&zeroDateTimeBehavior=CONVERT_TO_NULL&useFractionalSeconds=true&useUnicode=yes&characterEncoding=UTF-8&tinyInt1isBit=false&rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: kuk
    password: Qwpo1209
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        order_inserts: true
        order_updates: true

    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

weather:
  openweather: 13f95afecd7b5c2aff4b5104efd0e701
  publicweather: spDslsvoqEoOF8bCExVvcPRCqc0fqL9//Jt4q87Klb9GSzw6R9waE2uI2o7YHgZIEDXiAhNycfczlR9DIzKlYg==

slack:
#  모두의 일기
  token: TDD0B2813/B058SNUML0K/16dPemYK69rBsTQCaE6YCkDa
#  나에게 보내기
#  token: TDD0B2813/B0597E2JB6U/JPrKsA196JZYkGwNudgbh54d